'------------------------------------------------------------------------------
' <auto-generated>
'     Il codice è stato generato da uno strumento.
'     Versione runtime:4.0.30319.42000
'
'     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
'     il codice viene rigenerato.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Strings
    
    'Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    'tramite uno strumento quale ResGen o Visual Studio.
    'Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    'con l'opzione /str oppure ricompilare il progetto VS.
    '''<summary>
    '''  Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XtfViewerDataModel.Strings", GetType(Strings).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        '''  ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Channel {0} Information.
        '''</summary>
        Public Shared ReadOnly Property AppAvailGroupChannelInfo() As String
            Get
                Return ResourceManager.GetString("AppAvailGroupChannelInfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Main header.
        '''</summary>
        Public Shared ReadOnly Property AppAvailGroupMainHeader() As String
            Get
                Return ResourceManager.GetString("AppAvailGroupMainHeader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Packets of type: {0}.
        '''</summary>
        Public Shared ReadOnly Property AppAvailGroupPacketGroup() As String
            Get
                Return ResourceManager.GetString("AppAvailGroupPacketGroup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bathymetry.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBathy() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBathy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Beams per array.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBeamsPerArray() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBeamsPerArray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Beam width.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBeamWidth() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBeamWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Bytes per sample.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBytesPerSample() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBytesPerSample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Channel name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoChannelName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoChannelName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Correction flags.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoCorrectionFlags() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoCorrectionFlags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Frequency.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoFrequency() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Horizontal beam angle.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoHorizontalBeamAngle() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoHorizontalBeamAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset Pitch.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetPitch() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetPitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset Roll.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetRoll() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetRoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Port.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoPort() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoPort", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sample per channel.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoSamplesPerChannel() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoSamplesPerChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Starboard.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoStarboard() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoStarboard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Subbottom.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoSubbottom() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoSubbottom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sub channel number.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoSubChannelNumber() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoSubChannelNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Tilt angle.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoTiltAngle() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoTiltAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Type of Channel.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoTypeOfChannel() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoTypeOfChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Unipolar.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoUnipolar() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoUnipolar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Volt scale.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoVoltScale() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoVoltScale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a File Format.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderFileFormat() As String
            Get
                Return ResourceManager.GetString("XtfHeaderFileFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset Pitch.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetPitch() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetPitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset Roll.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetRoll() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetRoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a MRU offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Units of the navigation coordinates.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationCoordinateUnits() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationCoordinateUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Navigation latency.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationLatency() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationLatency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Navigation offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Navigation offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Navigation offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Navigation offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Notes.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNoteString() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNoteString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of bathymetry channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfBathymetryChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfBathymetryChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of echo strength channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfEchoStrengthChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfEchoStrengthChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of forward look arrays.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfForwardLookArrays() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfForwardLookArrays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of interferometry channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfInterferometryChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfInterferometryChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of snippet channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfSnippetChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfSnippetChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of sonar channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfSonarChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfSonarChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Recording Program Name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderRecordingProgramName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderRecordingProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Recording Program Version.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderRecordingProgramVersion() As String
            Get
                Return ResourceManager.GetString("XtfHeaderRecordingProgramVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Reference point height.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderReferencePointHeight() As String
            Get
                Return ResourceManager.GetString("XtfHeaderReferencePointHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sonar Name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSonarName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSonarName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sonar Type.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSonarType() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSonarType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a System Type.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSystemType() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSystemType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Name of this file.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderThisFileName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderThisFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Not available.
        '''</summary>
        Public Shared ReadOnly Property XtfInfoNotAvailable() As String
            Get
                Return ResourceManager.GetString("XtfInfoNotAvailable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of packets.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupCount() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a From {0} to {1}.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupFromTo() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupFromTo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Packet type.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupHeaderType() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupHeaderType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of bytes in this record.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupNumberBytesThisRecord() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupNumberBytesThisRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Number of channels to follow.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupNumberChannelsToFollow() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupNumberChannelsToFollow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Packet time.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupPacketTime() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupPacketTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Sub channel number.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupSubChannelNumber() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupSubChannelNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a System time reference in milliseconds.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupTimeTag() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupTimeTag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Degrees.
        '''</summary>
        Public Shared ReadOnly Property XtfUnitDegrees() As String
            Get
                Return ResourceManager.GetString("XtfUnitDegrees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Cerca una stringa localizzata simile a Meters.
        '''</summary>
        Public Shared ReadOnly Property XtfUnitMeters() As String
            Get
                Return ResourceManager.GetString("XtfUnitMeters", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
