'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Strings
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("XtfViewerCommonAssets.Strings", GetType(Strings).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beams per array.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBeamsPerArray() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBeamsPerArray", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Beam width.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBeamWidth() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBeamWidth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bytes per sample.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoBytesPerSample() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoBytesPerSample", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Channel name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoChannelName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoChannelName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Correction flags.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoCorrectionFlags() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoCorrectionFlags", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Frequency.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoFrequency() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoFrequency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Horizontal beam angle.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoHorizontalBeamAngle() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoHorizontalBeamAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset Pitch.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetPitch() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetPitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset Roll.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetRoll() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetRoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sample per channel.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoSamplesPerChannel() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoSamplesPerChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub channel number.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoSubChannelNumber() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoSubChannelNumber", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tilt angle.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoTiltAngle() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoTiltAngle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type of Channel.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoTypeOfChannel() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoTypeOfChannel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unipolar.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoUnipolar() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoUnipolar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volt scale.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderChannelInfoVoltScale() As String
            Get
                Return ResourceManager.GetString("XtfHeaderChannelInfoVoltScale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Format.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderFileFormat() As String
            Get
                Return ResourceManager.GetString("XtfHeaderFileFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset Pitch.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetPitch() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetPitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset Roll.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetRoll() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetRoll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MRU offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderMRUOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderMRUOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Units of the navigation coordinates.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationCoordinateUnits() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationCoordinateUnits", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation latency.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationLatency() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationLatency", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation offset X.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetX() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetX", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation offset Y.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetY() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetY", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation offset Yaw.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetYaw() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetYaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Navigation offset Z.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNavigationOffsetZ() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNavigationOffsetZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notes.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNoteString() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNoteString", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of bathymetry channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfBathymetryChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfBathymetryChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of echo strength channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfEchoStrengthChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfEchoStrengthChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of forward look arrays.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfForwardLookArrays() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfForwardLookArrays", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of interferometry channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfInterferometryChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfInterferometryChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of snippet channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfSnippetChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfSnippetChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of sonar channels.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderNumberOfSonarChannels() As String
            Get
                Return ResourceManager.GetString("XtfHeaderNumberOfSonarChannels", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recording Program Name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderRecordingProgramName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderRecordingProgramName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recording Program Version.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderRecordingProgramVersion() As String
            Get
                Return ResourceManager.GetString("XtfHeaderRecordingProgramVersion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reference point height.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderReferencePointHeight() As String
            Get
                Return ResourceManager.GetString("XtfHeaderReferencePointHeight", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sonar Name.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSonarName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSonarName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sonar Type.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSonarType() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSonarType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Type.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderSystemType() As String
            Get
                Return ResourceManager.GetString("XtfHeaderSystemType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name of this file.
        '''</summary>
        Public Shared ReadOnly Property XtfHeaderThisFileName() As String
            Get
                Return ResourceManager.GetString("XtfHeaderThisFileName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of packets.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupCount() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupCount", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Packet type.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupHeaderType() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupHeaderType", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of bytes in this record.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupNumberBytesThisRecord() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupNumberBytesThisRecord", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of channels to follow.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupNumberChannelsToFollow() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupNumberChannelsToFollow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Packet time.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupPacketTime() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupPacketTime", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sub channel number.
        '''</summary>
        Public Shared ReadOnly Property XtfPacketGroupSubChannelNumber() As String
            Get
                Return ResourceManager.GetString("XtfPacketGroupSubChannelNumber", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
